name: Daily JSON Update

on:
  schedule:
    - cron: '0 2 * * *' # This cron job runs at 2:00 AM UTC every day.
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Gemini CLI
        run: npm install -g @google/gemini-cli

      - name: Update JSON file using Gemini CLI
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Read the current JSON file content into a variable.
          CURRENT_JSON=$(cat hashtags.json)
          
          # Instruct Gemini to update the uses_count in the provided JSON.
          GEMINI_OUTPUT=$(gemini chat "Given the following JSON object: ${CURRENT_JSON}, please provide the exact same JSON object but with all the 'uses_count' values updated to a new, random number that is at least 10% higher than the current value. Ensure the format remains identical and provide ONLY the JSON object in your response, with no extra text or explanations.")
          
          # Use awk to extract the JSON object from the output.
          echo "$GEMINI_OUTPUT" | awk '/^{/,/}$/{
              if ($0 ~ /^{/) { start=1; json_content="" }
              if (start) { json_content = json_content $0 }
              if ($0 ~ /}$/) { print json_content; exit }
          }' | jq '.' > hashtags.json
          
          # Git configuration and commit.
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          git add hashtags.json
          git commit -m "Automated daily update of uses_count in hashtags.json"
          git push