name: Update JSON Data Weekly

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  run-data-processing:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run main.py script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

        run: python main.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data.json
          git commit -m "Update data.json with new uses_count values and last_update date"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}