name: Update Hashtags JSON

on:
 
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # The Google-managed action handles the Gemini CLI installation and authentication.
    # We no longer need the separate npm install or the 'gemini login' command.
    - name: Generate hashtags via Gemini CLI
      uses: google-github-actions/run-gemini-cli@v1
      id: generate_hashtags
      with:
        gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
        # The prompt is simplified to get a direct text response.
        prompt: "Give me 500 popular hashtags related to happiness, good vibes, and positive thinking. Respond with only the hashtags, separated by commas."

    - name: Update JSON with Python script
      run: |
        pip install google-generativeai
        
        # We now pass the generated content from the previous step to the Python script.
        # The 'outputs' property of the action contains the model's response.
        # We need to escape the output before passing it to the Python script
        # to ensure it's handled correctly.
        gemini_output="${{ steps.generate_hashtags.outputs.text }}"
        python update_hashtags.py "Happiness" "$gemini_output"

    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add hashtags.json
        git commit -m "chore: Daily hashtags update via Gemini CLI" || echo "No changes to commit"
        git push